# Generated by Django 3.1 on 2020-09-02 00:05

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comunidades', '0005_auto_20200819_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comunidad',
            name='resena',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
